#访问相关配置
server:
  port: 8010
  tomcat:
    uri-encoding: utf-8
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    druid:
      url: jdbc:oracle:thin:@192.168.1.100:1521:orcl
      username: mxalzsk
      password: hwmxalzsk-100
#配置solr服务地址
file:
# 文件存储路径
  save-path: D:\HanWei\数据访问服务20.07.16\resouce\Knowledge\file-manager
# 断点续传文件配置路径
  conf-path: D:\HanWei\数据访问服务20.07.16\resouce\Knowledge\file-manager\conf
# 索引创建路径
  index-path: D:\HanWei\数据访问服务20.07.16\resouce\index
md5:
  secure: d1WiQHyKnJb&Iels

mybatis-plus:
  mapper-locations: classpath:xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


